### ISSUE TITLE
Cannot build on 4.18.5-arch1-1-ARCH

### ISSUE THREAD

**Issue by hifi25nl** [cilynx/rtl88x2BU_WiFi_linux_v5.2.4.4_26334.20180126_COEX20171012-5044#5]
I cannot build on 4.18.5-arch1-1-ARCH gcc version 8.2.1+20180831-1

 ` CC [M]  /media/linux/Downloads/Temp/rtl88x2bu/rtl88x2BU_WiFi_linux_v5.2.4.4_26334.20180126_COEX20171012-5044/hal/hal_mcc.o
  CC [M]  /media/linux/Downloads/Temp/rtl88x2bu/rtl88x2BU_WiFi_linux_v5.2.4.4_26334.20180126_COEX20171012-5044/hal/hal_hci/hal_usb.o
/media/linux/Downloads/Temp/rtl88x2bu/rtl88x2BU_WiFi_linux_v5.2.4.4_26334.20180126_COEX20171012-5044/hal/hal_hci/hal_usb.c: In function ‘usb_init_recv_priv’:
/media/linux/Downloads/Temp/rtl88x2bu/rtl88x2BU_WiFi_linux_v5.2.4.4_26334.20180126_COEX20171012-5044/hal/hal_hci/hal_usb.c:28:8: error: cast between incompatible function types from ‘void (*)(void *)’ to ‘void (*)(long unsigned int)’ [-Werror=cast-function-type]
        (void(*)(unsigned long))usb_recv_tasklet,
        ^
cc1: all warnings being treated as errors
make[2]: *** [scripts/Makefile.build:318: /media/linux/Downloads/Temp/rtl88x2bu/rtl88x2BU_WiFi_linux_v5.2.4.4_26334.20180126_COEX20171012-5044/hal/hal_hci/hal_usb.o] Error 1
make[1]: *** [Makefile:1500: _module_/media/linux/Downloads/Temp/rtl88x2bu/rtl88x2BU_WiFi_linux_v5.2.4.4_26334.20180126_COEX20171012-5044] Error 2
make[1]: Leaving directory '/usr/lib/modules/4.18.5-arch1-1-ARCH/build'
make: *** [Makefile:1794: modules] Error 2
`

**Comment by hifi25nl** [comment]
It compiles fine omitting the line about -Werror in make file.

**Comment by drewwalters96** [comment]
Same here on `4.18.7-arch1-1-ARCH`:

```
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/4.18.7-arch1-1-ARCH/build M=/var/lib/dkms/rtl88x2bu/5.2.4.4/build  modules
make[1]: Entering directory '/usr/lib/modules/4.18.7-arch1-1-ARCH/build'
  CC [M]  /var/lib/dkms/rtl88x2bu/5.2.4.4/build/core/rtw_cmd.o
  CC [M]  /var/lib/dkms/rtl88x2bu/5.2.4.4/build/core/rtw_security.o
  CC [M]  /var/lib/dkms/rtl88x2bu/5.2.4.4/build/core/rtw_debug.o
  CC [M]  /var/lib/dkms/rtl88x2bu/5.2.4.4/build/core/rtw_io.o
  CC [M]  /var/lib/dkms/rtl88x2bu/5.2.4.4/build/core/rtw_ioctl_query.o
  CC [M]  /var/lib/dkms/rtl88x2bu/5.2.4.4/build/core/rtw_ioctl_set.o
  CC [M]  /var/lib/dkms/rtl88x2bu/5.2.4.4/build/core/rtw_ieee80211.o
  CC [M]  /var/lib/dkms/rtl88x2bu/5.2.4.4/build/core/rtw_mlme.o
  CC [M]  /var/lib/dkms/rtl88x2bu/5.2.4.4/build/core/rtw_mlme_ext.o
  CC [M]  /var/lib/dkms/rtl88x2bu/5.2.4.4/build/core/rtw_mi.o
  CC [M]  /var/lib/dkms/rtl88x2bu/5.2.4.4/build/core/rtw_wlan_util.o
  CC [M]  /var/lib/dkms/rtl88x2bu/5.2.4.4/build/core/rtw_vht.o
  CC [M]  /var/lib/dkms/rtl88x2bu/5.2.4.4/build/core/rtw_pwrctrl.o
  CC [M]  /var/lib/dkms/rtl88x2bu/5.2.4.4/build/core/rtw_rf.o
  CC [M]  /var/lib/dkms/rtl88x2bu/5.2.4.4/build/core/rtw_recv.o
  CC [M]  /var/lib/dkms/rtl88x2bu/5.2.4.4/build/core/rtw_sta_mgt.o
  CC [M]  /var/lib/dkms/rtl88x2bu/5.2.4.4/build/core/rtw_ap.o
  CC [M]  /var/lib/dkms/rtl88x2bu/5.2.4.4/build/core/rtw_xmit.o
  CC [M]  /var/lib/dkms/rtl88x2bu/5.2.4.4/build/core/rtw_p2p.o
  CC [M]  /var/lib/dkms/rtl88x2bu/5.2.4.4/build/core/rtw_tdls.o
  CC [M]  /var/lib/dkms/rtl88x2bu/5.2.4.4/build/core/rtw_br_ext.o
  CC [M]  /var/lib/dkms/rtl88x2bu/5.2.4.4/build/core/rtw_iol.o
  CC [M]  /var/lib/dkms/rtl88x2bu/5.2.4.4/build/core/rtw_sreset.o
  CC [M]  /var/lib/dkms/rtl88x2bu/5.2.4.4/build/core/rtw_btcoex_wifionly.o
  CC [M]  /var/lib/dkms/rtl88x2bu/5.2.4.4/build/core/rtw_btcoex.o
  CC [M]  /var/lib/dkms/rtl88x2bu/5.2.4.4/build/core/rtw_beamforming.o
  CC [M]  /var/lib/dkms/rtl88x2bu/5.2.4.4/build/core/rtw_odm.o
  CC [M]  /var/lib/dkms/rtl88x2bu/5.2.4.4/build/core/efuse/rtw_efuse.o
  CC [M]  /var/lib/dkms/rtl88x2bu/5.2.4.4/build/os_dep/osdep_service.o
  CC [M]  /var/lib/dkms/rtl88x2bu/5.2.4.4/build/os_dep/linux/os_intfs.o
  CC [M]  /var/lib/dkms/rtl88x2bu/5.2.4.4/build/os_dep/linux/usb_intf.o
  CC [M]  /var/lib/dkms/rtl88x2bu/5.2.4.4/build/os_dep/linux/usb_ops_linux.o
  CC [M]  /var/lib/dkms/rtl88x2bu/5.2.4.4/build/os_dep/linux/ioctl_linux.o
  CC [M]  /var/lib/dkms/rtl88x2bu/5.2.4.4/build/os_dep/linux/xmit_linux.o
  CC [M]  /var/lib/dkms/rtl88x2bu/5.2.4.4/build/os_dep/linux/mlme_linux.o
  CC [M]  /var/lib/dkms/rtl88x2bu/5.2.4.4/build/os_dep/linux/recv_linux.o
  CC [M]  /var/lib/dkms/rtl88x2bu/5.2.4.4/build/os_dep/linux/ioctl_cfg80211.o
  CC [M]  /var/lib/dkms/rtl88x2bu/5.2.4.4/build/os_dep/linux/rtw_cfgvendor.o
  CC [M]  /var/lib/dkms/rtl88x2bu/5.2.4.4/build/os_dep/linux/wifi_regd.o
  CC [M]  /var/lib/dkms/rtl88x2bu/5.2.4.4/build/os_dep/linux/rtw_android.o
  CC [M]  /var/lib/dkms/rtl88x2bu/5.2.4.4/build/os_dep/linux/rtw_proc.o
  CC [M]  /var/lib/dkms/rtl88x2bu/5.2.4.4/build/os_dep/linux/ioctl_mp.o
  CC [M]  /var/lib/dkms/rtl88x2bu/5.2.4.4/build/hal/hal_intf.o
  CC [M]  /var/lib/dkms/rtl88x2bu/5.2.4.4/build/hal/hal_com.o
  CC [M]  /var/lib/dkms/rtl88x2bu/5.2.4.4/build/hal/hal_com_phycfg.o
  CC [M]  /var/lib/dkms/rtl88x2bu/5.2.4.4/build/hal/hal_phy.o
  CC [M]  /var/lib/dkms/rtl88x2bu/5.2.4.4/build/hal/hal_dm.o
  CC [M]  /var/lib/dkms/rtl88x2bu/5.2.4.4/build/hal/hal_btcoex_wifionly.o
  CC [M]  /var/lib/dkms/rtl88x2bu/5.2.4.4/build/hal/hal_btcoex.o
  CC [M]  /var/lib/dkms/rtl88x2bu/5.2.4.4/build/hal/hal_mp.o
  CC [M]  /var/lib/dkms/rtl88x2bu/5.2.4.4/build/hal/hal_mcc.o
  CC [M]  /var/lib/dkms/rtl88x2bu/5.2.4.4/build/hal/hal_hci/hal_usb.o
  CC [M]  /var/lib/dkms/rtl88x2bu/5.2.4.4/build/hal/led/hal_usb_led.o
  CC [M]  /var/lib/dkms/rtl88x2bu/5.2.4.4/build/hal/hal_halmac.o
  CC [M]  /var/lib/dkms/rtl88x2bu/5.2.4.4/build/hal/rtl8822b/rtl8822b_halinit.o
  CC [M]  /var/lib/dkms/rtl88x2bu/5.2.4.4/build/hal/rtl8822b/rtl8822b_mac.o
/var/lib/dkms/rtl88x2bu/5.2.4.4/build/hal/hal_hci/hal_usb.c: In function ‘usb_init_recv_priv’:
/var/lib/dkms/rtl88x2bu/5.2.4.4/build/hal/hal_hci/hal_usb.c:28:8: error: cast between incompatible function types from ‘void (*)(void *)’ to ‘void (*)(long unsigned int)’ [-Werror=cast-function-type]                                                                         
        (void(*)(unsigned long))usb_recv_tasklet,
        ^
cc1: all warnings being treated as errors
make[2]: *** [scripts/Makefile.build:317: /var/lib/dkms/rtl88x2bu/5.2.4.4/build/hal/hal_hci/hal_usb.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [Makefile:1504: _module_/var/lib/dkms/rtl88x2bu/5.2.4.4/build] Error 2
make[1]: Leaving directory '/usr/lib/modules/4.18.7-arch1-1-ARCH/build'
make: *** [Makefile:1794: modules] Error 2
```

As suggested above, removing or commenting line 6 from `Makefile` will provide a temporary, successful installation.
